### ISSUE TITLE
Simulation: main function not returning ends in nonsense error

### ISSUE THREAD

**Issue by petspats** [petspats/pyha#93]
```
    def main(self, b):
        pass
```

```
INFO:pyha.simulation.simulation_interface:Running HW_MODEL simulation!
WARNING:pyha.simulation.simulation_interface:"expected=None", all sims must output: 
[None None]
Traceback (most recent call last):
  File "/home/gaspar/git/thesis/examples/basic_class/class.py", line 34, in <module>
    test_basic()
  File "/home/gaspar/git/thesis/examples/basic_class/class.py", line 30, in test_basic
    dir_path='/home/gaspar/git/thesis/playground')
  File "/home/gaspar/git/pyha/pyha/simulation/simulation_interface.py", line 313, in assert_sim_match
    np.testing.assert_allclose(expected[skip_first:], hw_y[skip_first:len(expected)], rtol, atol=atol)
  File "/home/gaspar/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/gaspar/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 779, in assert_array_compare
    val = safe_comparison(x, y)
  File "/home/gaspar/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 720, in safe_comparison
    return comparison(*args, **kwargs)
  File "/home/gaspar/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 1406, in compare
    equal_nan=equal_nan)
  File "/home/gaspar/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 2557, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

This should say something helpful instead. Or just skip assert on empty lists?

**Comment by gasparka** [comment]
Models with no input have come up multiple times no, this needs to be supported.
No output is not useful hardware.. but it comes up when the goal is just to test some conversion functionality. Solution is to convert the files but skip simulations?

**Comment by gasparka** [comment]
Models without input cannot really be simulated as input is related to clock. No input = no clock, how many cycles should it run?

**Comment by gasparka** [comment]
Workaround:
Add dummy input/output.
